# By default, Compose reads two files, a docker-compose.yml
# and an optional docker-compose.override.yml.
# This file overrides or extends fields.
version: '3.9'
services:

  backend:
    build:
      target: stage
      args:
        PYTHON_MINOR_VERSION: ${PYTHON_MINOR_VERSION:-3.9}
    restart: always

  db:
    restart: always
    volumes:
      - ./conf/db-init-user.sh:/docker-entrypoint-initdb.d/db-init-user.sh:ro
      - ./conf/example-db.env:/example-db.env:ro
    environment:
      - POSTGRES_PASSWORD_FILE=/example-db.env
      - DB_ENV_FILE=/example-db.env

  web:
    restart: always
    volumes:
      - ./conf/nginx-default.conf.template:/etc/nginx/templates/default.conf.template:ro

  ssl:
    restart: always
    volumes:
      - ./conf/ssl-entrypoint.sh:/ssl-entrypoint.sh:ro
