version: '3.9'

services:

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: prod
    image: ${BACKEND_IMAGE:-maxreshetnik/portfolio:latest}
    volumes:
      - media:/home/portfolio/media
      - static:/home/portfolio/static
    depends_on:
      - db
      - cache

  db:
    image: postgres:14.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
        
  cache:
    image: memcached:alpine
    restart: always
  
  web:
    image: nginx:alpine
    environment:
      - APP_SERVER_LOCATION=backend:8000
      - SSL_DIR=/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - static:/usr/share/nginx/static:ro
      - media:/usr/share/nginx/media:ro
      - ssl_files:/etc/nginx/ssl
    depends_on:
      - backend

volumes:
  media:
  static:
  db_data:
  ssl_files:

networks:
  default:
    name: portfolio_net