version: '3.9'
services:

  backend:
    build:
      context: ../
      target: dev
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"

  db:
    ports:
      - "5432:5432"

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    secrets:
    configs:
      - source: nginx_site.conf
        target: /etc/nginx/sites-available/portfolio
      - source: nginx_site.conf
        target: /etc/nginx/sites-enabled/portfolio

  memcached:
    ports:
      - "11211:11211"

configs:
  nginx_site.conf:
    file: ./conf/nginx-site.conf
  init_user_db.sh:
    file: ./conf/init-user-db.sh

secrets:
  secrets.json:
    file: ./conf/secrets.dev.json
  db.env:
    file: ./conf/db.dev.env
