#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$PORTFOLIO_DB_USER"
    WITH PASSWORD "$PORTFOLIO_DB_PASSWORD"
    NOSUPERUSER CREATEDB NOCREATEROLE;
    CREATE DATABASE "$PORTFOLIO_DB_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$PORTFOLIO_DB_USER" TO "$PORTFOLIO_DB_USER";
    ALTER ROLE "$PORTFOLIO_DB_USER" SET client_encoding TO 'utf8';
    ALTER ROLE "$PORTFOLIO_DB_USER" SET default_transaction_isolation TO 'read committed';
    ALTER ROLE "$PORTFOLIO_DB_USER" SET timezone TO 'UTC';
EOSQL
