# Generated by Django 3.2.3 on 2021-09-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210913_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main.portfolio'),
            preserve_default=False,
        ),
    ]
