# Generated by Django 3.2.3 on 2021-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedback_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='specialization',
            field=models.SlugField(default='python'),
            preserve_default=False,
        ),
    ]
