# Generated by Django 3.2.3 on 2021-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_portfolio_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='specialization',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
