# Generated by Django 3.2.3 on 2021-09-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_portfolio_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
