# This file overrides and extends parent files 
# -f docker-compose.yml -f docker-compose.override.yml
version: '3.9'

services:

  backend:
    image: portfolio:dev
    build:
      target: stage
      args:
        PYTHON_BUILD: ""
        PROJECT_NAME: "portfolio"
        PROJECT_DIR: "/workspace"
    environment:
        RACK_ENV: "dev"
        DJANGO_SETTINGS_MODULE: "portfolio.settings.dev"
        GUNICORN_CMD_ARGS: "--bind=0.0.0.0:8001 --reload --access-logfile -"
        PGHOST: "localhost"
    env_file:
      - ./conf/example-db.env
    command: sleep infinity
    container_name: portfolio_backend_dev
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /workspace
        volume:
          nocopy: true
      - type: bind
        source: ./media
        target: /home/portfolio/media
        volume:
          nocopy: true
    # Runs app on the same network as the database container, 
    # allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    
  db:
    container_name: portfolio_db_dev
    restart: unless-stopped

  cache:
    container_name: portfolio_cache_dev
    restart: unless-stopped

  web:
    container_name: portfolio_web_dev
    environment:
      APP_SERVER_LOCATION: db:8001
    restart: unless-stopped
    healthcheck:
      disable: true
    volumes:
      - type: bind
        source: ./media
        target: /usr/share/nginx/media
        read_only: true

  ssl:
    container_name: portfolio_ssl_dev
    restart: unless-stopped

networks:
  default:
    name: portfolio_net_dev
