# Generated by Django 3.2.3 on 2021-07-13 18:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_specification_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='available_qty',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='available quantity'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='image',
            field=models.ImageField(blank=True, help_text='Minimal image sizes is 400x400 pixels. Max upload file size up to 10 MB.', null=True, upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='pre_packing',
            field=models.DecimalField(decimal_places=3, default='1', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='pre-packing'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='specification',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default='0', help_text='Special price replaces the discount price, 0 is disabled', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight_vol',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='weight/volume'),
        ),
    ]
