# Generated by Django 3.2.3 on 2021-07-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_specification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 600x600 pixels. Max upload file size up to 10 MB.', upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 600x600 pixels. Max upload file size up to 10 MB.', upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 600x600 pixels. Max upload file size up to 10 MB.', upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='image',
            field=models.ImageField(blank=True, help_text='Minimal image sizes is 600x600 pixels. Max upload file size up to 10 MB.', upload_to='shop/'),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='image',
            field=models.ImageField(help_text='Minimal image sizes is 600x600 pixels. Max upload file size up to 10 MB.', upload_to='shop/'),
        ),
    ]
