# Generated by Django 3.2.3 on 2021-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20210728_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'cart'},
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='PC', max_length=3),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='KG', max_length=3, verbose_name='unit for weight/volume'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='PC', max_length=3),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='KG', max_length=3, verbose_name='unit for weight/volume'),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='PC', max_length=3),
        ),
        migrations.AlterField(
            model_name='smartphoneproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='KG', max_length=3, verbose_name='unit for weight/volume'),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='unit',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='PC', max_length=3),
        ),
        migrations.AlterField(
            model_name='tvproduct',
            name='unit_for_weight_vol',
            field=models.CharField(choices=[('Weight', (('KG', 'kilo'), ('LB', 'pound'))), ('Volume', (('L', 'liter'), ('GAL', 'gallon'))), ('PC', 'piece'), ('PCK', 'pack'), ('PR', 'pair'), ('BTL', 'bottle'), ('LT', 'lot')], default='KG', max_length=3, verbose_name='unit for weight/volume'),
        ),
    ]
