# Generated by Django 3.2.3 on 2021-08-27 17:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_auto_20210827_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_added',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'C')), fields=('user',), name='unique_cart_user'),
        ),
    ]
