# Generated by Django 3.2.3 on 2021-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20210827_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='customers',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='specification',
            constraint=models.CheckConstraint(check=models.Q(('available_qty__gte', 0)), name='qty_gte_0'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
