# Generated by Django 3.2.3 on 2021-09-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20210901_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='specification',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
