# Generated by Django 3.2.3 on 2021-09-12 15:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0055_auto_20210912_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Cart'), (2, 'Processing'), (3, 'Shipping'), (4, 'Finished')])),
                ('address', models.TextField(blank=True)),
                ('order_cost', models.DecimalField(decimal_places=2, default='0', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserved', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.specification')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='specs',
            field=models.ManyToManyField(through='shop.OrderItem', to='shop.Specification'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'specification'), name='order_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('user',), name='unique_user_cart'),
        ),
    ]
