# Generated by Django 3.2.3 on 2021-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_auto_20210912_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='by_default',
            field=models.BooleanField(default=False),
        ),
    ]
