# Generated by Django 3.2.3 on 2021-09-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_shippingaddress_by_default'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('by_default', True)), fields=('user',), name='unique_default_address'),
        ),
    ]
