# This workflow will build docker images, run tests and lint python code.

name: Testing

on:
  push:
    branches-ignore: [ master ]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set output image name and tags
        id: image_id
        shell: bash
        run: |
          echo "::set-output name=image::${{ secrets.DOCKER_HUB_USERNAME }}/${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=image_tag::${GITHUB_SHA::12}"
          echo "::set-output name=repo_name::${GITHUB_REPOSITORY#*/}"

      - name: Add execute permissions for context files
        run: chmod -R +x .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: stage
          load: true
          tags: ${{ steps.image_id.outputs.image }}:${{ steps.image_id.outputs.image_tag }}
          cache-from: type=registry,ref=${{ steps.image_id.outputs.image }}:buildcache
          cache-to: type=registry,ref=${{ steps.image_id.outputs.image }}:buildcache,mode=max

      - name: Up backend and deps
        env:
          BACKEND_IMAGE: ${{ steps.image_id.outputs.image }}:${{ steps.image_id.outputs.image_tag }}
        run: |
          make up s="--no-build backend"
          docker ps

      - name: Lint with flake8
        run: make backend_lint

      - name: Test
        run: make backend_test_cov
