name: Deployment

on:
  push:
    branches: [ cicd ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        run: echo "$HOME"
      - run: echo -en "${{ secrets.DOCKER_HUB_USERNAME }}" >> "$HOME/ddddd.txt"
      - run: cat "$HOME/ddddd.txt"
      - run: ls -la "$HOME"
      - run: ssh

