name: Test

on:
  push:
    branches: [ test ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        run: docker-compose --version

      - name: Add permissions
        run: chmod -R +x .

      - name: test permissions
        run: ls -la
